create table public.books (
  id bigint generated by default as identity not null,
  isbn character varying not null,
  rating bigint null,
  review text null,
  date_finished date null,
  title text null,
  author_name text null,
  description text null,
  cover_url text null,
  constraint books_pkey primary key (id)
) TABLESPACE pg_default;

create table public.users (
  id bigint generated by default as identity not null,
  username text not null,
  password text not null default ''::text,
  constraint users_pkey primary key (id),
  constraint users_password_key unique (password),
  constraint users_username_key unique (username)
) TABLESPACE pg_default;